# https://github.com/helix-editor/helix/wiki/How-to-install-the-default-language-servers

# https://github.com/helix-editor/helix/issues/1942#issuecomment-1086891320
[[language]]
name = "markdown"
scope = "source.md"
injection-regex = "md|markdown"
file-types = ["md", "markdown", "PULLREQ_EDITMSG", "mkd", "mdwn", "mdown", "markdn", "mdtxt", "mdtext", "workbook", "qmd", "txt"]
roots = [".marksman.toml"]
language-servers = [ "marksman", "ltex-ls" ]
indent = { tab-width = 2, unit = "  " }

[language-server.ltex-ls]
command = "ltex-ls"
config.completionEnabled = true
config.ltex.language = "en-CA"
config.ltex.dictionary.en-CA = ["Boulderz", "LJI", "Knocean", "OMOP"]
config.ltex.dictionary.en-US = ["Boulderz", "LJI", "Knocean", "OMOP"]
